[DEFAULT]
debug = false

[api_settings]
bind_host = 0.0.0.0
bind_port = 9876

[database]
connection = mysql+pymysql://octavia:changeit@127.0.0.1/octavia

[keystone_authtoken]
www_authenticate_uri = http://127.0.0.1:5000
auth_url = http://127.0.0.1:5000
auth_type = password
project_domain_name = Default
user_domain_name = Default
project_name = service
username = octavia
password = changeit

[oslo_policy]
policy_file = /etc/octavia/policy.yaml